name: "CI: Check Code Style"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.py'

jobs:
  run-prettify:
    runs-on: ubuntu-latest
    name: "Job: Check Code Style"
    steps:
      # Checkout to repository
      - name: Checkout
        uses: actions/checkout@v4
      # Setup PDM
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      # Install only ruff as dependency
      - name: Install Ruff
        run: pdm add -dG linting ruff
      # Get all changed python file paths
      - name: Get all changed python file paths
        id: changes
        uses: tj-actions/changed-files@v44
        with:
          files: |  
            **.py
      # Activate venv
      - name: Activate venv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      # Run ruff on changed files
      - name: Run ruff on changed files
        env:
          CHANGED_FILES: ${{ steps.changes.outputs.all_changed_files }}
        run: |
          for file in ${CHANGED_FILES}; do
            ruff check "$file"
            ruff format "$file"
          done
