name: "CI: Comment Checkout Instructions"

on:
  pull_request:
    branches:
      - main
    types:
      - opened

permissions:
  id-token: write
  pull-requests: write

jobs:
  write-instructions:
    runs-on: ubuntu-latest
    name: "Job: Comment Checkout Instructions"
    steps:
      # Checkout to repository
      - name: Checkout
        uses: actions/checkout@v4
      # Comment on PR
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ### :rocket: Checkout Instructions
          
            ``` bash
            git fetch origin
            git checkout ${{ github.head_ref }}
            ```
            
            Happy Coding!
