name: Check release draft

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited, labeled, unlabeled]

jobs:
  verify-labels:
    runs-on: ubuntu-latest
    name: A job to verify labels
    if: github.event.pull_request.merged == false
    steps:
      # Generate a github token
      - name: Generate token
        id: token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          revoke_token: true
      # Checkout to repository
      - name: Checkout
        uses: actions/checkout@v3
      # Varify lables
      - name: Verify labels
        uses: mauroalderete/action-verify-labels@v1
        with:
          github-token: ${{ steps.token.outputs.token }}
          some: 'release: feature, release: bug-fix, release: sprint-deliverables'
