name: "Write checkout instructions"
on:
  pull_request:
    branches:
      - main
    types: [opened]
jobs:
  comment_pr:
    runs-on: ubuntu-latest
    name: A job to comment a PR and provide checkout instructions
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          revoke_token: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          message: |
            ### :rocket: Checkout Instructions

            Make sure your **origin** is set to: **[https://github.com/amosproj/amos2024ss06-health-ai-framework.git](https://github.com/amosproj/amos2024ss06-health-ai-framework.git)**
          
            ``` bash
            git fetch origin
            git checkout ${{ github.head_ref }}
            ```
            
            Happy Coding!
