name: "CI: Check Lint and Format Python Code"

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.py'

jobs:
  check-lint-format:
    runs-on: ubuntu-latest
    name: "Job: Check Lint and Format Python Code"
    steps:
      # Checkout to repository
      - name: Checkout
        uses: actions/checkout@v4
      # Setup Ruff
      - name: Setup Ruff
        uses: chartboost/ruff-action@v1
        with:
          changed-files: 'true'
