name: "CI: Verify Labels on Pull Request"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - labeled
      - unlabeled

permissions:
  id-token: write
  pull-requests: write

jobs:
  verify-labels:
    runs-on: ubuntu-latest
    name: "Job: Verify Labels on Pull Request"
    if: github.event.pull_request.merged == false
    steps:
      # Checkout to repository
      - name: Checkout
        uses: actions/checkout@v4
      # Varify labels
      - name: Verify labels
        uses: mauroalderete/action-verify-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          some: 'release: feature, release: bug-fix, release: sprint-deliverables, release: maintenance, release: refactor'
